name:  equilibrium
description: Calendário de Estudos e Autodiagnóstico ENEM

# Informações do desenvolvedor
homepage: https://github.com/ThiagoWaldrich/flutter_enem_equilibrium
repository: https://github.com/ThiagoWaldrich/flutter_enem_equilibrium

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  
  flutter:
    sdk: flutter
  
  #json
  json_annotation: ^4.9.0
  # Gerenciamento de Estado
  provider: ^6.1.1
  marquee: ^2.2.3
  easy_debounce: ^2.0.3
  
  # Banco de Dados Local
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  sqflite_common_ffi: ^2.3.1
  path: ^1.8.3
  
  
  # Persistência de Dados
  shared_preferences: ^2.2.2
  
  # UI Components
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  table_calendar: ^3.0.9
  intl_utils: ^2.8.13
  
  # Gráficos
  fl_chart: ^0.65.0
  
  # Imagens
  image_picker: ^1.0.5
  image: ^4.1.3
  
  
  # PDF
  pdf: ^3.10.7
  printing: ^5.11.1
  
  # File Picker
  file_picker: ^6.1.1
  msix: ^3.16.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/model.ico

# flutter_icons:
#   image_path: "assets/model.ico"
#   android: true
#   ios: true
#   windows: true
#   macos: true
#   linux: true
#   web: true