name: equilibrium
description: Calendário de Estudos e Autodiagnóstico ENEM

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Gerenciamento de Estado
  provider: ^6.1.1
  
  # Banco de Dados Local
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  sqflite_common_ffi: ^2.3.1
  path: ^1.8.3
  
  
  # Persistência de Dados
  shared_preferences: ^2.2.2
  
  # UI Components
  cupertino_icons: ^1.0.6
  intl: ^0.18.1
  table_calendar: ^3.0.9
  
  # Gráficos
  fl_chart: ^0.65.0
  
  # Imagens
  image_picker: ^1.0.5
  image: ^4.1.3
  
  # CSV
  csv: ^5.1.1
  
  # PDF
  pdf: ^3.10.7
  printing: ^5.11.1
  
  # File Picker
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true